sudo: required

language: android
jdk: oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=30
    - ANDROID_BUILD_TOOLS_VERSION=30.0.0

android:
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL
before_script:
  - yes | sdkmanager "platforms;android-30"

script:
  - chmod +x ./gradlew
  - ./gradlew test
  - ./gradlew assemblerelease

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file: $TRAVIS_BUILD_DIR/app/build/outputs/apk/release/apk-release.apk
  skip_cleanup: true
  name: dev-build-$TRAVIS_TAG
  body: Automatic Build of $TRAVIS_BRANCH ($TRAVIS_COMMIT) build by Travis CI On $(date + '%F %T %Z').
  prerelease: true
  overwrite: true
  target_commitish: $TRAVIS_COMMIT
  on:
    tags: true

after_deploy:
  - rm -rf $TRAVIS_BUILD_DIR/app/build/outputs


